spring:
  application:
    name: community
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.web: TRACE
    root: debug

app:
  image:
    base-url: http://localhost:8080/

springdoc:
  override-with-generic-response: false

